name: explore_widget
description: Explore All Widget

publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_preview: ^1.1.0

  camera: ^0.10.1 #official
  camerawesome:
    git:
      url: https://github.com/Apparence-io/camera_awesome
      ref: 3ca70b46387e46c67b90e4f6eef40f6c3f49de07
  flutter_layout_grid: ^2.0.1
  flutter_rating_bar: ^4.0.1
  lottie: ^2.0.0
  rive: ^0.10.1
  super_editor: ^0.2.3+1
  video_player: ^2.4.10 #official
  webview_flutter: ^4.2.0

  path_provider: ^2.0.2 #official

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  logging: ^1.1.1
  dio: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/rive/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: FontLato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          style: italic
          weight: 700
    - family: FontPoppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
        - asset: assets/fonts/Poppins-Bold.otf
          weight: 700